package com.viborotto.javasdkdynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;

import java.io.Serializable;

public class MusicId implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String artist;

    @DynamoDBHashKey(attributeName = "id") // partition key
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBRangeKey(attributeName="artist") // sort key
    public String getArtist() { return artist;}
    public void setArtist(String artist) {this.artist = artist;}
}
