package com.viborotto.javasdkdynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

import java.io.Serializable;

@DynamoDBTable(tableName="Music")
public class Music implements Serializable {

    private static final long serialVersionUID = -4282005207341771716L;

    @Id
    private MusicId musicId;

    private String id;
    private String artist;
    private String songTitle;
    private String albumTitle;
    private int year;
//    private Pictures pictures;

    @DynamoDBHashKey(attributeName = "music_id") // partition key
    @DynamoDBAutoGeneratedKey
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    @DynamoDBRangeKey(attributeName="artist") // sort key
    public String getArtist() { return artist;}
    public void setArtist(String artist) {this.artist = artist;}

    @DynamoDBAttribute(attributeName="song_title")
    public String getSongTitle() { return songTitle;}
    public void setSongTitle(String songTitle) {this.songTitle = songTitle;}

    @DynamoDBAttribute(attributeName = "album_title")
    public String getAlbumTitle() { return albumTitle;}
    public void setAlbumTitle(String albumTitle) {this.albumTitle = albumTitle;}

    @DynamoDBAttribute(attributeName = "year")
    public int getYear() { return year; }
    public void setYear(int year) { this.year = year; }

    public Music() {
    }

    public Music(String id, String artist, String songTitle, String albumTitle, int year) {
        this.id = id;
        this.artist = artist;
        this.songTitle = songTitle;
        this.albumTitle = albumTitle;
        this.year = year;
    }

    //    @DynamoDBAttribute(attributeName="Pictures")
//    public Pictures getPictures() { return pictures;}
//    public void setPictures(Pictures pictures) {this.pictures = pictures;}

//    @DynamoDBDocument
//    public static class Pictures {
//        private String frontView;
//        private String rearView;
//        private String sideView;
//
//        @DynamoDBAttribute(attributeName = "FrontView")
//        public String getFrontView() { return frontView; }
//        public void setFrontView(String frontView) { this.frontView = frontView; }
//
//        @DynamoDBAttribute(attributeName = "RearView")
//        public String getRearView() { return rearView; }
//        public void setRearView(String rearView) { this.rearView = rearView; }
//
//        @DynamoDBAttribute(attributeName = "SideView")
//        public String getSideView() { return sideView; }
//        public void setSideView(String sideView) { this.sideView = sideView; }
//
//    }

}
